//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_address
    {
        public int id { get; set; }
        public string Icons { get; set; }
        public string Titles { get; set; }
        public string Address { get; set; }
        public string AnchorLinks { get; set; }
    }
}
