//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_doctors
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Degree { get; set; }
        public string Timing { get; set; }
        public string Profile { get; set; }
    }
}
