//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string User_Type { get; set; }
        public string User_Image { get; set; }
        public string Password { get; set; }
        public Nullable<int> userCount { get; set; }
        public string DOB { get; set; }
        public string education { get; set; }
        public string bio { get; set; }
        public string experience { get; set; }
        public string location { get; set; }
        public string title { get; set; }
        public Nullable<int> isPublicProfile { get; set; }
    }
}
